# Generated by Django 2.1 on 2018-08-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.IntegerField(default=0)),
                ('present_classes', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=30)),
                ('roll_number', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('course_opted', models.CharField(choices=[('WEB', 'Web Development'), ('NTWRK', 'Networking'), ('ML', 'Machine Learning'), ('DROID', 'Android')], max_length=15)),
                ('valid_till', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='attendancetracker',
            name='roll_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll', to='core.Users'),
        ),
    ]
