# Generated by Django 2.1 on 2018-11-02 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.IntegerField(default=0)),
                ('present_classes', models.IntegerField(default=0)),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('domain', models.CharField(choices=[('WEB', 'Web Development'), ('NTWRK', 'Networking'), ('ML', 'Machine Learning'), ('DROID', 'Android')], max_length=15)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=30)),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('course_opted', models.CharField(choices=[('WEB', 'Web Development'), ('NTWRK', 'Networking'), ('ML', 'Machine Learning'), ('DROID', 'Android')], max_length=15)),
                ('active_from', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.IntegerField(default=365)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.AddField(
            model_name='attendancetracker',
            name='roll_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll', to='core.Student'),
        ),
    ]
