# Generated by Django 2.1 on 2018-09-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180827_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('full_name',)},
        ),
    ]
