# Generated by Django 2.1 on 2018-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180913_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetracker',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
