# Generated by Django 2.1 on 2018-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180921_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='expiry',
            field=models.IntegerField(default=365),
        ),
    ]
